
export const GET_MOVIES_BY_NAME_REQUEST = "GET_MOVIES_LIST_REQUEST";
export const GET_MOVIES_BY_NAME_RESPONSE = "GET_MOVIES_LIST_RESPONSE";
export const EDIT_MOVIE = "EDIT_MOVIE"
export const DELETE_MOVIE = "DELETE_MOVIE"
